# Generated by Django 6.0.4 on 2026-05-05 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0002_add_saldo_a_favor'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=13)),
                ('razon_social', models.CharField(max_length=300)),
                ('nombre_comercial', models.CharField(blank=True, max_length=300)),
                ('direccion', models.CharField(max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('establecimiento', models.CharField(default='001', max_length=3)),
                ('punto_emision', models.CharField(default='001', max_length=3)),
                ('ambiente', models.CharField(choices=[('pruebas', 'Pruebas'), ('produccion', 'Producción')], default='pruebas', max_length=15)),
                ('iva_porcentaje', models.IntegerField(default=15)),
                ('obligado_contabilidad', models.BooleanField(default=False)),
                ('certificado_p12', models.TextField(blank=True)),
                ('clave_certificado', models.TextField(blank=True)),
                ('cert_titular', models.CharField(blank=True, max_length=400)),
                ('cert_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('siguiente_secuencial', models.PositiveIntegerField(default=1)),
                ('contingencia_activa', models.BooleanField(default=False)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración SRI',
                'verbose_name_plural': 'Configuración SRI',
            },
        ),
        migrations.CreateModel(
            name='FacturaSRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20)),
                ('clave_acceso', models.CharField(blank=True, max_length=49, null=True, unique=True)),
                ('fecha_emision', models.DateField()),
                ('ambiente', models.CharField(default='pruebas', max_length=15)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('emitida', 'Emitida'), ('autorizada', 'Autorizada'), ('rechazada', 'Rechazada'), ('anulada', 'Anulada')], default='borrador', max_length=15)),
                ('subtotal_0', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('subtotal_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('iva_porcentaje', models.IntegerField(default=15)),
                ('iva_valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('xml_firmado', models.TextField(blank=True)),
                ('sri_numero_autorizacion', models.CharField(blank=True, max_length=80)),
                ('sri_fecha_autorizacion', models.DateTimeField(blank=True, null=True)),
                ('sri_respuesta', models.TextField(blank=True)),
                ('sri_intentos_recepcion', models.IntegerField(default=0)),
                ('es_contingencia', models.BooleanField(default=False)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('notas', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente')),
                ('creada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('venta', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='factura_sri', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Factura SRI',
                'verbose_name_plural': 'Facturas SRI',
                'ordering': ['-creada_en'],
            },
        ),
        migrations.CreateModel(
            name='ItemFacturaSRI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=300)),
                ('cantidad', models.DecimalField(decimal_places=4, default=1, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=4, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('aplica_iva', models.BooleanField(default=True)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=12)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='facturacion.facturasri')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.AddIndex(
            model_name='facturasri',
            index=models.Index(fields=['estado'], name='facturacion_estado_a88407_idx'),
        ),
        migrations.AddIndex(
            model_name='facturasri',
            index=models.Index(fields=['clave_acceso'], name='facturacion_clave_a_81f66e_idx'),
        ),
        migrations.AddIndex(
            model_name='facturasri',
            index=models.Index(fields=['cliente', 'estado'], name='facturacion_cliente_8d0436_idx'),
        ),
    ]
