# Generated by Django 6.0.4 on 2026-04-21 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('deudores', '0001_initial'),
        ('inventario', '0001_initial'),
        ('ventas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='adelanto',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='adelantos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='adelantoitem',
            name='adelanto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='deudores.adelanto'),
        ),
        migrations.AddField(
            model_name='adelantoitem',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas', to='clientes.cliente'),
        ),
        migrations.AddField(
            model_name='deuda',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deudas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deuda',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deuda', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='pago',
            name='vendedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_registrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='adelanto',
            index=models.Index(fields=['cliente', 'estado'], name='deudores_ad_cliente_90906e_idx'),
        ),
        migrations.AddIndex(
            model_name='deuda',
            index=models.Index(fields=['cliente', 'estado'], name='deudores_de_cliente_dda416_idx'),
        ),
        migrations.AddIndex(
            model_name='deuda',
            index=models.Index(fields=['fecha_vencimiento'], name='deudores_de_fecha_v_b6ebc1_idx'),
        ),
        migrations.AddIndex(
            model_name='pago',
            index=models.Index(fields=['tipo', 'referencia_id'], name='deudores_pa_tipo_ad965d_idx'),
        ),
    ]
