# Generated by Django 6.0.4 on 2026-04-21 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='saldo_a_favor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
