# Generated by Django 6.0.4 on 2026-04-29 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('blusas', 'Blusas'), ('camisas', 'Camisas'), ('camisetas', 'Camisetas'), ('pantalones', 'Pantalones'), ('vestidos', 'Vestidos'), ('faldas', 'Faldas'), ('chaquetas', 'Chaquetas'), ('zapatos', 'Zapatos'), ('accesorios', 'Accesorios'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Catálogo producto',
                'verbose_name_plural': 'Catálogo productos',
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variantes', to='inventario.catalogoproducto'),
        ),
    ]
