# Generated by Django 6.0.4 on 2026-05-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_data_catalogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogoproducto',
            name='precio_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio máximo sugerido (techo recomendado).', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='catalogoproducto',
            name='precio_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Precio mínimo permitido al vender (no se puede bajar de aquí).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='catalogoproducto',
            name='precio_base',
            field=models.DecimalField(decimal_places=2, help_text='Precio sugerido / por defecto.', max_digits=10),
        ),
    ]
