# Generated by Django 6.0.4 on 2026-06-12 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0008_backfill_etiquetas_y_codigos'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ultimo_ingreso_stock',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
