# Generated by Django 6.0.4 on 2026-06-13 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0009_producto_ultimo_ingreso_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_anterior',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(blank=True, db_index=True, max_length=100)),
                ('nombre_producto', models.CharField(blank=True, max_length=250)),
                ('tipo', models.CharField(choices=[('creacion', 'Creación de variante'), ('ajuste', 'Ajuste manual de stock'), ('venta', 'Venta al contado'), ('venta_credito', 'Venta a crédito'), ('apartado', 'Apartado (reserva)'), ('apartado_completado', 'Apartado entregado'), ('apartado_cancelado', 'Apartado cancelado'), ('compra', 'Compra a proveedor')], db_index=True, max_length=25)),
                ('stock_anterior', models.IntegerField()),
                ('stock_nuevo', models.IntegerField()),
                ('reservado_anterior', models.IntegerField(blank=True, null=True)),
                ('reservado_nuevo', models.IntegerField(blank=True, null=True)),
                ('referencia', models.CharField(blank=True, help_text='p. ej. "Venta #123", "Compra #45"', max_length=120)),
                ('nota', models.CharField(blank=True, max_length=250)),
                ('creado_en', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventario.producto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_inventario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de inventario',
                'verbose_name_plural': 'Movimientos de inventario',
                'ordering': ['-creado_en', '-id'],
                'indexes': [models.Index(fields=['producto', '-creado_en'], name='inventario__product_3f95bc_idx')],
            },
        ),
    ]
