# Generated by Django 6.0.4 on 2026-05-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionGeneral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_negocio', models.CharField(default='Sistema Tienda', max_length=200)),
                ('slogan', models.CharField(blank=True, max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='configuracion/')),
                ('direccion', models.CharField(blank=True, max_length=300)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('mensaje_nota_venta', models.TextField(blank=True, default='¡Gracias por su compra!', help_text='Mensaje que aparece al pie de la nota de venta.')),
                ('stock_minimo_alerta', models.PositiveIntegerField(default=5, help_text='Cuando el stock disponible de una variante baje de este valor, se muestra como "stock bajo".')),
                ('dias_alerta_vencimiento', models.PositiveIntegerField(default=7, help_text='Días de anticipación para alertar deudas o adelantos por vencer.')),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración general',
                'verbose_name_plural': 'Configuración general',
            },
        ),
    ]
