# Generated by Django 6.0.4 on 2026-05-06 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='color_primario',
            field=models.CharField(default='#4F46E5', help_text='Color principal del sistema (botones, links, badges).', max_length=7),
        ),
    ]
