# Generated by Django 6.0.4 on 2026-05-06 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuracion', '0002_configuraciongeneral_color_primario'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuraciongeneral',
            name='cliente_obligatorio_venta',
            field=models.BooleanField(default=False, help_text='Exigir cliente en cada venta (si está apagado, "Consumidor final" es válido).'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='imprimir_auto_nota',
            field=models.BooleanField(default=False, help_text='Abrir automáticamente la nota de venta al cobrar.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='mostrar_logo_en_nota',
            field=models.BooleanField(default=True, help_text='Incluir el logo del negocio en notas de venta y RIDE.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='mostrar_vendedor_en_nota',
            field=models.BooleanField(default=True, help_text='Mostrar el nombre del vendedor que registró la venta en la nota.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='permitir_vender_sin_stock',
            field=models.BooleanField(default=False, help_text='Permitir registrar ventas aunque el producto no tenga stock disponible.'),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='precio_fuera_rango_modo',
            field=models.CharField(choices=[('bloquear', 'Bloquear'), ('advertir', 'Advertir'), ('permitir', 'Permitir')], default='advertir', help_text='Qué hacer cuando el vendedor pone un precio fuera del rango min/max del producto.', max_length=12),
        ),
        migrations.AddField(
            model_name='configuraciongeneral',
            name='sonido_escaneo',
            field=models.BooleanField(default=True, help_text='Reproducir un beep al detectar un código de barras en el POS.'),
        ),
    ]
