# Generated by Django 6.0.4 on 2026-05-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='forma_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'QR / Transferencia')], default='efectivo', help_text='Cómo cobró el vendedor (efectivo / tarjeta / QR)', max_length=15),
        ),
    ]
